app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("ckeditor/", include("ckeditor_uploader.urls")),
        path("", include("blog.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "APP Administration"
admin.site.site_title = "APP Admin Portal"
admin.site.index_title = "Welcome to APP Admin Portal"

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"


urlpatterns = [
    path("", views.index, name="home"),
    path("accounts/login/", views.login, name="login"),
    path("register", views.register, name="register"),
    path("subscription/<slug:slug>/", views.subscription, name="subscription"),
    path("about/", views.about, name="about"),
    path("privacypolicy/", views.privacypolicy, name="privacypolicy"),
    path("cancellationypolicy/", views.cancellationypolicy, name="cancellationypolicy"),
    path("logout/", views.logout_view, name="logout"),
    path("terms/", views.terms, name="terms"),
    path("subscriptions/", views.subscriptions, name="subscriptions"),
    path("subscribe/<int:id>", views.subscribe, name="subscribe"),
    path("singlesubscribe/<int:id>", views.single_subscribe, name="singlesubscribe"),
    path("article/<slug:slug>", views.article, name="article"),
    path("articles/<slug:slug>/", views.articles, name="articles"),
    path("tags/<slug:slug>/", views.taggedarticles, name="taggedarticles"),
    path("webzin-tags/<slug:slug>", views.webzintaggedarticles, name="webzin-tags"),
    path("videos/", views.videos, name="videos"),
    path("video/<int:id>", views.video, name="video"),
    path("author/<int:id>", views.article_of_author, name="author"),
    path("webzin-author/<int:id>", views.webzin_article_of_author, name="webzinauthor"),
    path("latest-webzin", views.webzinLatest, name="latest"),
    path("webzins", views.webzinViewAll, name="webzins"),
    path("webzin/<slug:slug>", views.SingleWebzin, name="webzin"),
    path("webzinarticles/<slug:slug>/", views.webzinarticles, name="webzinarticles"),
    path("webzinarticle/<slug:slug>", views.SingleWebzinArticle, name="webzinarticle"),
    path("subscriptionhandler/", views.SubscriptionHandler, name="subscriptionhandler"),
    path(
        "singlesubscriptionhandler/",
        views.SingleSubscriptionHandler,
        name="singlesubscriptionhandler",
    ),
    path("add-referrel-code/", views.add_referrel_code, name="add-referrel-code"),
    path(
        "add-referrel-code-single/",
        views.add_referrel_code_single,
        name="add-referrel-code-single",
    ),
]

templates/web/AuthorsArticle.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Author{% endblock %}

{% block content %}

    <main>
        <div class="container">
            <div class="hot-tags pt-30 pb-30 font-small align-self-center">
                <div class="widget-header-3">
                    <div class="row align-self-center">
                        <div class="col-md-4 align-self-center">
                            <h5 class="widget-title">Featured posts</h5>
                        </div>
                        {% include 'web/partials/hottags.html' %}
                    </div>
                </div>
            </div>

           
            <div class="author-bio p-30 mt-50 border-radius-10 bg-white wow fadeIn animated">
                <div class="author-image mb-30">
                    <a href="#"><img src="{{author.photo.crop.90x90}}" alt="" class="avatar"></a>
                </div>
                <div class="author-info">
                    <h4 class="font-weight-bold mb-20"><span class="vcard author"><span class="fn"><a href="#" title="Posted by Barbara Cartland" rel="author">{{author.name}}</a></span></span>
                    </h4>
                    <h5 class="text-muted">About author</h5>
                    <div class="author-description text-muted">{{author.about}}</div>
                    <a href="#" class="author-bio-link mb-md-0 mb-3"></a>
                    <div class="author-social">
                        <ul class="author-social-icons">
                            <li class="author-social-link-facebook"><a href="#" target="_blank"><i class="ti-facebook"></i></a></li>
                            <li class="author-social-link-twitter"><a href="#" target="_blank"><i class="ti-twitter-alt"></i></a></li>
                            <li class="author-social-link-pinterest"><a href="#" target="_blank"><i class="ti-pinterest"></i></a></li>
                            <li class="author-social-link-instagram"><a href="#" target="_blank"><i class="ti-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="bg-grey pt-50 pb-50 ">
                <div class="container ">
                    <div class="row ">
                        <div class="col-lg-12 ">
        
                           <!-- Short Read -->
                           {% for PageItem in PageItems %}
                           <div class="post-module-2" id="{{PageItem.category.id}}">
                               <div class="widget-header-1 position-relative mb-30 wow fadeInUp animated ">
                                   <h5 class="mt-5 mb-30">{{PageItem.category.name}}</h5>
                               </div>
                               <div class="loop-list loop-list-style-1">
                                   <div class="row ">
                                       {% for article in PageItem.articles %}
                                       <article class="col-md-6 col-lg-6 mb-40 wow fadeInUp animated pr-0 p-4">
                                           <div class="post-card-1 border-radius-10 hover-up ">
                                               <div class="row">
                                                   <div class="col-lg-5 col-md-5 p-2 pl-4">
                                                       <div class="post-thumb thumb-overlay img-hover-slide position-relative" style="background-image: url({{article.article_image.crop.113x130}}) ">
                                                           <a class="img-link " href="{% url 'blog:article' article.slug %}"></a>
                                                           <ul class="social-share ">
                                                               <li><a href="# "><i class="elegant-icon social_share "></i></a>
                                                               </li>
                                                               <li><a class="fb " href="# " title="Share on Facebook " target="_blank "><i
                                                                           class="elegant-icon social_facebook "></i></a></li>
                                                               <li><a class="tw " href="# " target="_blank " title="Tweet now "><i
                                                                           class="elegant-icon social_twitter "></i></a></li>
                                                               <li><a class="pt " href="# " target="_blank " title="Pin it "><i
                                                                           class="elegant-icon social_pinterest "></i></a></li>
                                                           </ul>
                                                       </div>
                                                   </div>
                                                   <div class="col-lg-7 col-md-7">
                                                       <div class="post-content p-10 ">
                                                           <div class="d-flex post-card-content ">
                                                               <h6 class="post-title mb-20 font-weight-900 ">
                                                                   <a href="{% url 'blog:article' article.slug %}">{{article.title}} </a>
                                                               </h6>
                                                               {% for author in article.author.all %}
                                                                <p> - {{author.name}}</p>
                                                                {% endfor %}
                                                           </div>
                                                       </div>
                                                   </div>
                                               </div>  
                                           </div>
                                       </article>
                                       {% endfor  %}
                                   </div>
                                   <div class="row"><div class="col-12"><a href="/articles/{{PageItem.category.slug}}/"><button class="float-right btn btn-radius bg-primary text-white ml-15 font-small box-shadow">Read more</button></a></div></div>
                               </div>
                           </div>
                           {% endfor %}
        
        
                           <!-- Short Read -->
                            <hr>
        
                            <!-- <div class="pagination-area mb-30 wow fadeInUp animated ">
                                <nav aria-label="Page navigation example ">
                                    <ul class="pagination justify-content-start ">
                                        <li class="page-item "><a class="page-link " href="# "><i
                                                    class="elegant-icon arrow_left "></i></a></li>
                                        <li class="page-item active "><a class="page-link " href="# ">01</a></li>
                                        <li class="page-item "><a class="page-link " href="# ">02</a></li>
                                        <li class="page-item "><a class="page-link " href="# ">03</a></li>
                                        <li class="page-item "><a class="page-link " href="# ">04</a></li>
                                        <li class="page-item "><a class="page-link " href="# "><i
                                                    class="elegant-icon arrow_right "></i></a></li>
                                    </ul>
                                </nav>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
    </main>

{% endblock %}

{% block javascript %}

{% endblock %}

templates/web/WebZineAuthorsArticle.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Author{% endblock %}

{% block content %}

    <main>
        <div class="container">
            <div class="hot-tags pt-30 pb-30 font-small align-self-center">
                <div class="widget-header-3">
                    <div class="row align-self-center">
                        <div class="col-md-4 align-self-center">
                            <h5 class="widget-title">Featured posts</h5>
                        </div>
                        {% include 'web/partials/hottags.html' %}
                    </div>
                </div>
            </div>

           
            <div class="author-bio p-30 mt-50 border-radius-10 bg-white wow fadeIn animated">
                <div class="author-image mb-30">
                    <a href="#"><img src="{{author.photo.crop.90x90}}" alt="" class="avatar"></a>
                </div>
                <div class="author-info">
                    <h4 class="font-weight-bold mb-20"><span class="vcard author"><span class="fn"><a href="#" title="Posted by Barbara Cartland" rel="author">{{author.name}}</a></span></span>
                    </h4>
                    <h5 class="text-muted">About author</h5>
                    <div class="author-description text-muted">{{author.about}}</div>
                    <a href="#" class="author-bio-link mb-md-0 mb-3"></a>
                    <div class="author-social">
                        <ul class="author-social-icons">
                            <li class="author-social-link-facebook"><a href="#" target="_blank"><i class="ti-facebook"></i></a></li>
                            <li class="author-social-link-twitter"><a href="#" target="_blank"><i class="ti-twitter-alt"></i></a></li>
                            <li class="author-social-link-pinterest"><a href="#" target="_blank"><i class="ti-pinterest"></i></a></li>
                            <li class="author-social-link-instagram"><a href="#" target="_blank"><i class="ti-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="bg-grey pt-50 pb-50 ">
                <div class="container ">
                    <div class="row ">
                        <div class="col-lg-12 ">
        
                           <!-- Short Read -->
                           {% for article in webzinearticle %}
                            
                           <div class="post-module-2" id="{{article.category.id}}">
                               <div class="widget-header-1 position-relative mb-30 wow fadeInUp animated ">
                                   <h5 class="mt-5 mb-30">{{article.webzinarticlecategory.name}}</h5>
                               </div>
                               <div class="loop-list loop-list-style-1">
                                   <div class="row ">
                                       <article class="col-md-6 col-lg-6 mb-40 wow fadeInUp animated pr-0 p-4">
                                           <div class="post-card-1 border-radius-10 hover-up ">
                                               <div class="row">
                                                   <div class="col-lg-5 col-md-5 p-2 pl-4">
                                                       <div class="post-thumb thumb-overlay img-hover-slide position-relative">
                                                           <a class="img-link " href="{% url 'blog:webzinarticle' article.slug %}">
                                                            <img src="{{article.article_image.url}}" alt="">
                                                           </a>
                                                           <ul class="social-share ">
                                                               <li><a href="# "><i class="elegant-icon social_share "></i></a>
                                                               </li>
                                                               <li><a class="fb " href="# " title="Share on Facebook " target="_blank "><i
                                                                           class="elegant-icon social_facebook "></i></a></li>
                                                               <li><a class="tw " href="# " target="_blank " title="Tweet now "><i
                                                                           class="elegant-icon social_twitter "></i></a></li>
                                                               <li><a class="pt " href="# " target="_blank " title="Pin it "><i
                                                                           class="elegant-icon social_pinterest "></i></a></li>
                                                           </ul>
                                                       </div>
                                                   </div>
                                                   <div class="col-lg-7 col-md-7">
                                                       <div class="post-content p-10 ">
                                                           <div class="d-flex post-card-content ">
                                                               <h6 class="post-title mb-20 font-weight-900 ">
                                                                   <a href="{% url 'blog:webzinarticle' article.slug %}">{{article.title}} </a>
                                                               </h6>
                                                               <p> - {{article.author.name}}</p>
                                                           </div>
                                                       </div>
                                                   </div>
                                               </div>  
                                           </div>
                                       </article>
                                      
                                   </div>
                                   <div class="row"><div class="col-12"><a href="{% url 'blog:articles' article.webzinarticlecategory.slug %}"><button class="float-right btn btn-radius bg-primary text-white ml-15 font-small box-shadow">Read more</button></a></div></div>
                               </div>
                           </div>
                           {% endfor %}
        
        
                           <!-- Short Read -->
                            <hr>
        
                            <div class="pagination-area mb-30 wow fadeInUp animated ">
                                <nav aria-label="Page navigation example ">
                                    <ul class="pagination justify-content-start ">
                                        <li class="page-item "><a class="page-link " href="# "><i
                                                    class="elegant-icon arrow_left "></i></a></li>
                                        <li class="page-item active "><a class="page-link " href="# ">01</a></li>
                                        <li class="page-item "><a class="page-link " href="# ">02</a></li>
                                        <li class="page-item "><a class="page-link " href="# ">03</a></li>
                                        <li class="page-item "><a class="page-link " href="# ">04</a></li>
                                        <li class="page-item "><a class="page-link " href="# "><i
                                                    class="elegant-icon arrow_right "></i></a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>







            
    </main>

{% endblock %}

{% block javascript %}
<script>
    //   page specific scripts
    console.log("This will run only in index.html")
</script>
{% endblock %}

templates/web/subscriptions.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

<main class="bg-grey pt-80 pb-50">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-6 col-md-10">
        <div class="login_wrap widget-taber-content p-30 bg-white border-radius-10">
          <div class="padding_eight_all bg-white">
            <div class="heading_s1 text-center">
              <h3 class="mb-30 font-weight-900">Subscription</h3>
            </div>
            <table class="table">
              <thead>
                <tr>
                  <th>Subscription</th>
                  <th>Validity</th>
                  <th> </th>
                </tr>
              </thead>
              <tbody>
                {% for subscription in subscriptionplan %}
                <tr>
                  <th>{{subscription.subscription_title}}</th>
                  <td>{{subscription.validity_in_month}} Month {% if subscription.is_include_special_edition %}Included
                    Special Edtion{% endif %}</td>
                  <td><a href="{% url 'blog:subscribe' subscription.id %}"><button type="button"
                        class="btn btn-success">{{subscription.amount}} / - Subscribe</button></a></td>
                </tr>
                {% endfor %}


              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

{% block javascript %}
<script>
  $(document).ready(function () {
  })
  //   page specific scripts
  console.log("This will run only in index.html")
</script>
{% endblock %}

templates/web/webzinsinglearticle.html
{% extends 'web/base.html' %} {% load static %} {% block title %}Home{% endblock %}

{% block meta %}
<meta name="title" content="{{webzinArticle.webzinarticlecategory.name}}">
<meta name="description" content="{{webzinArticle.title}}">
<meta property="og:image" content="{{webzinArticle.article_image.crop.1000x600}}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="{{request.build_absolute_uri}}">
<meta property="og:title" content="{{webzinArticle.webzinarticlecategory.name}}">
<meta property="og:description" content="{{webzinArticle.title}}">
<!-- Twitter -->
<meta property="twitter:card" content="{{webzinArticle.webzinarticlecategory.name}}">
<meta property="twitter:url" content="{{request.build_absolute_uri}}">
<meta property="twitter:title" content="{{webzinArticle.webzinarticlecategory.name}}">
<meta property="twitter:description" content="{{webzinArticle.title}}">
{% endblock meta %}
{% block content %}
<main class="bg-grey pb-30">
    <div class="container single-content">


        <!-- Title ,Author and Share links  -->
        <div class="entry-header entry-header-style-1 mb-50 pt-50">
            <h1 class="entry-title mb-50 font-weight-900">
                {{webzinArticle.title}}
            </h1>

            <div class="row">

                <!-- Author -->
                <div class="col-md-6">
                    <div class="entry-meta align-items-center meta-2 font-small color-muted">
                        <p class="mb-5">
                            <a class="author-avatar" href="{% url 'blog:webzinauthor' webzinArticle.author.id %}"><img
                                    class="img-circle" src="{{webzinArticle.author.photo.crop.50x50}}" alt=""></a>
                            By <a href="{% url 'blog:webzinauthor' webzinArticle.author.id %}"><span
                                    class="author-name font-weight-bold">{{webzinArticle.author.name}}</span></a>
                        </p>
                        <span class="mr-10"> {{ webzinArticle.published|date:"M d, Y" }} </span>
                        <span class="has-dot"> {{ webzinArticle.read_time}} mins read</span>
                    </div>
                </div>
                <!-- Author -->


                <div class="col-md-6 text-right d-none d-md-inline">
                    <ul class="header-social-network d-inline-block list-inline mr-15">
                        <li class="list-inline-item text-muted"><span>Share this: </span></li>
                        <li class="list-inline-item"><a class="social-icon fb text-xs-center" target="_blank"
                                href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"><i
                                    class="elegant-icon social_facebook"></i></a></li>
                        <li class="list-inline-item"><a class="social-icon tw text-xs-center" target="_blank"
                                href="https://www.twitter.com/intent/tweet?text={{instance.title|urlencode}}%20{{request.build_absolute_uri}}"><i
                                    class="elegant-icon social_twitter "></i></a></li>
                        <li class="list-inline-item"><a class="social-icon pt text-xs-center" target="_blank"
                                href="https://api.whatsapp.com/send?text=*{{instance.title|urlencode}}*%0A%0A{{instance.summary|urlencode}}%0A{{request.build_absolute_uri}}"><i
                                    class="fa-brands fa-whatsapp"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>

    

        <!--Image-->
        <figure class="image aricle-head mb-30 m-auto text-center border-radius-10">
            <span class="category-name-in-figure">{{webzinArticle.webzinarticlecategory.name}}</span>
            <img class="border-radius-10" src="{{webzinArticle.article_image.crop.1000x600}}" alt="post-title" />
        </figure>
        <!--figure-->

        <div class="article-content-area rich-text-area">
            {% if is_subscribed %}
            {% for content in contents %} {{ content.content | safe }} {% endfor %}
            
            {% else %}
            {% for content in contents %} {{ content.content | safe }} {% endfor %}
            <div class="text-center">
                <a href="{% url 'blog:subscription' slug %}" class="btn btn-success text-white">Subscribe to Read more
                    ..</a>
            </div>
            {% endif %}
        </div>

        <article class="entry-wraper mb-50">
            <!-- Tags -->
            <div class="entry-bottom mt-50 mb-30 wow fadeIn animated">
                <div class="col-md-8 text-md-right font-small align-self-center">
                    <p class="d-inline-block mr-5 mb-0"><i class="elegant-icon  icon_tag_alt mr-5 text-muted"></i>Tags:
                    </p>
                    <ul class="list-inline d-inline-block tags">
                        {% for tag in atricleTags %}
                        <li class="list-inline-item"><a href="{% url 'blog:webzin-tags' tag.slug %}">#{{tag.name}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
           
            <div class="author-bio p-30 mt-50 border-radius-10 bg-white wow fadeIn animated">
                <div class="author-image mb-30">
                    <a href="#"><img src="{{webzinArticle.author.photo.crop.100x100}}" alt="" class="avatar"></a>
                </div>
                <div class="author-info">
                    <h4 class="font-weight-bold mb-20"><span class="vcard author"><span class="fn"><a href="{% url 'blog:webzinauthor' webzinArticle.author.id %}"
                                    title="Posted by Barbara Cartland"
                                    rel="author">{{webzinArticle.author.name}}</a></span></span>
                    </h4>
                    <h5 class="text-muted">About author</h5>
                    <div class="author-description text-muted">{{webzinArticle.author.about}} </div>
                    <!-- <a href="author.html" class="author-bio-link mb-md-0 mb-3">View all posts (125)</a> -->
                    <div class="author-social">
                        <ul class="author-social-icons">
                            <li class="author-social-link-facebook"><a href="#" target="_blank"><i
                                        class="ti-facebook"></i></a></li>
                            <li class="author-social-link-twitter"><a href="#" target="_blank"><i
                                        class="ti-twitter-alt"></i></a></li>
                            <li class="author-social-link-pinterest"><a href="#" target="_blank"><i
                                        class="ti-pinterest"></i></a></li>
                            <li class="author-social-link-instagram"><a href="#" target="_blank"><i
                                        class="ti-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>


            <!--related posts-->
            <div class="related-posts">
                <div class="post-module-3">
                    <div class="widget-header-2 position-relative mb-30">
                        <h5 class="mt-5 mb-30">Related posts</h5>
                    </div>
                    <div class="loop-list loop-list-style-1">


                        {% for article in relatedarticles %}
                        <article class="col-md-6 mb-40 wow fadeInUp animated ">
                            <div class="post-card-1 border-radius-10 hover-up ">
                                <div class="row">
                                    <div class="col-lg-5 col-md-5 p-4    pl-4">
                                        <div class="post-thumb thumb-overlay img-hover-slide position-relative"
                                            style="background-image: url({{article.article_image.crop.332x130}}) ">
                                            <a class="img-link" href="{% url 'blog:webzinarticle' article.slug %}"></a>
                                            <ul class="social-share ">
                                                <li><a href="# "><i class="elegant-icon social_share "></i></a></li>
                                                <li><a class="fb " target="_blank"
                                                        href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"
                                                        title="Facebook "><i
                                                            class="elegant-icon social_facebook "></i></a></li>
                                                <li><a class="tw " target="_blank"
                                                        href="https://www.twitter.com/intent/tweet?text={{article.webzinarticlecategory.name|urlencode}}%20{{request.build_absolute_uri}}"
                                                        title="Tweet now "><i
                                                            class="elegant-icon social_twitter "></i></a></li>
                                                <li><a class="pt "
                                                        href="https://api.whatsapp.com/send?text=*{{article.webzinarticlecategory.name|urlencode}}*%0A%0A{{article.title|urlencode}}%0A{{request.build_absolute_uri}}"
                                                        target="_blank " title="Pin it "><i
                                                            class="fa-brands fa-whatsapp"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-lg-7 col-md-7">
                                        <div class="post-content p-10 ">
                                            <div class="d-flex post-card-content ">
                                                <h6 class="post-title mb-20 font-weight-900 ">
                                                    <a href="{% url 'blog:webzinarticle' article.slug %}">{{article.title}}
                                                    </a>
                                                </h6>
                                                <p> - {{article.author.name}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </article>
        
    </div>
    <!--container-->
</main>
{% endblock %} {% block javascript %}
<script>


    //   page specific scripts
    console.log("This will run only in index.html")
</script>
{% endblock %}