app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("ckeditor/", include("ckeditor_uploader.urls")),
        path("", include("blog.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "APP Administration"
admin.site.site_title = "APP Admin Portal"
admin.site.index_title = "Welcome to APP Admin Portal"

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"


urlpatterns = [
    path("", views.index, name="home"),
    path("accounts/login/", views.login, name="login"),
    path("register", views.register, name="register"),
    path("subscription/<slug:slug>/", views.subscription, name="subscription"),
    path("about/", views.about, name="about"),
    path("privacypolicy/", views.privacypolicy, name="privacypolicy"),
    path("cancellationypolicy/", views.cancellationypolicy, name="cancellationypolicy"),
    path("logout/", views.logout_view, name="logout"),
    path("terms/", views.terms, name="terms"),
    path("subscriptions/", views.subscriptions, name="subscriptions"),
    path("subscribe/<int:id>", views.subscribe, name="subscribe"),
    path("singlesubscribe/<int:id>", views.single_subscribe, name="singlesubscribe"),
    path("article/<slug:slug>", views.article, name="article"),
    path("articles/<slug:slug>/", views.articles, name="articles"),
    path("tags/<slug:slug>/", views.taggedarticles, name="taggedarticles"),
    path("webzin-tags/<slug:slug>", views.webzintaggedarticles, name="webzin-tags"),
    path("videos/", views.videos, name="videos"),
    path("video/<int:id>", views.video, name="video"),
    path("author/<int:id>", views.article_of_author, name="author"),
    path("webzin-author/<int:id>", views.webzin_article_of_author, name="webzinauthor"),
    path("latest-webzin", views.webzinLatest, name="latest"),
    path("webzins", views.webzinViewAll, name="webzins"),
    path("webzin/<slug:slug>", views.SingleWebzin, name="webzin"),
    path("webzinarticles/<slug:slug>/", views.webzinarticles, name="webzinarticles"),
    path("webzinarticle/<slug:slug>", views.SingleWebzinArticle, name="webzinarticle"),
    path("subscriptionhandler/", views.SubscriptionHandler, name="subscriptionhandler"),
    path(
        "singlesubscriptionhandler/",
        views.SingleSubscriptionHandler,
        name="singlesubscriptionhandler",
    ),
    path("add-referrel-code/", views.add_referrel_code, name="add-referrel-code"),
    path(
        "add-referrel-code-single/",
        views.add_referrel_code_single,
        name="add-referrel-code-single",
    ),
]

templates/web/partials/header.html
{% load static %}

<header class="main-header header-style-1 font-heading">
    <div class="header-top">
        <div class="container">
            <div class="row pt-10-header pb-1-header">
                <div class="col-md-3 col-6">
                    {% if is_webzine %}
                    <a href="{% url 'blog:home' %}"><img class="logo webzine-width"
                            src="{% static 'web/assets/imgs/theme/webzine-1.png' %}" alt=""></a>
                    <p class="logo-title  webzinelogo-title">Liberation @ Thinking</p>
                    {% else %}
                    <a href="{% url 'blog:webzins' %}"><img class="logo webzinelog2"
                            src="{% static 'web/assets/imgs/theme/finallogo.png' %}" alt=""></a>
                    <p class="logo-title">Liberation @ Thinking</p>

                    {% endif %}
                </div>
                <div class="col-md-9 col-6 text-right header-top-right ">
                    <!-- <ul class="list-inline nav-topbar d-none d-md-inline">
                        <li class="list-inline-item menu-item-has-children"><a href="#">Layouts</a>
                            <ul class="sub-menu font-small">
                                <li class="menu-item-has-children"><a href="#">Pages</a>
                                    <ul class="sub-menu font-small">
                                        <li><a href="page-about.html">About</a></li>
                                        <li><a href="page-contact.html">Contact</a></li>
                                        <li><a href="page-typography.html">Typography</a></li>
                                        <li><a href="page-register.html">Register</a></li>
                                        <li><a href="page-login.html">Login</a></li>
                                        <li><a href="page-search.html">Search</a></li>
                                        <li><a href="page-author.html">Author</a></li>
                                        <li><a href="page-404.html">404 page</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-has-children"><a href="#">Category</a>
                                    <ul class="sub-menu font-small">
                                        <li><a href="category-list.html">List layout</a></li>
                                        <li><a href="category-grid.html">Grid layout</a></li>
                                        <li><a href="category-masonry.html">Masonry layout</a></li>
                                        <li><a href="category-big.html">Big layout</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-has-children"><a href="#">Single post</a>
                                    <ul class="sub-menu font-small">
                                        <li><a href="single.html">Default</a></li>
                                        <li><a href="single-2.html">Big image</a></li>
                                        <li><a href="single-3.html">Left image</a></li>
                                        <li><a href="single-4.html">With sidebar</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="list-inline-item"><a href="http://demos.alithemes.com/html/stories/docs/"><i
                                    class="elegant-icon icon_document_alt mr-5"></i>Document</a></li>
                    </ul> -->
                    <!-- <span class="vertical-divider mr-20 ml-20 d-none d-md-inline"></span>
                    <button class="search-icon d-none d-md-inline"><span class="mr-15 text-muted font-small"><i
                                class="elegant-icon icon_search mr-5"></i>Search</span></button> -->

                    <div class="float-right header-tools text-muted font-small d-sm-none d-none d-lg-block">
                        <ul class="header-social-network d-inline-block list-inline mr-15">
                            <li class="list-inline-item"><a class="social-icon fb text-xs-center" target="_blank"
                                    href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"><i
                                        class="elegant-icon social_facebook"></i></a></li>
                            <li class="list-inline-item"><a class="social-icon tw text-xs-center" target="_blank"
                                    href="https://www.twitter.com/intent/tweet?text={{instance.title|urlencode}}%20{{request.build_absolute_uri}}"><i
                                        class="elegant-icon social_twitter "></i></a></li>
                            <li class="list-inline-item"><a class="social-icon pt text-xs-center" target="_blank"
                                    href="https://api.whatsapp.com/send?text=*{{instance.title|urlencode}}*%0A%0A{{instance.summary|urlencode}}%0A{{request.build_absolute_uri}}"><i
                                        class="fa-brands fa-whatsapp"></i></a></li>
                            {% if not request.user.is_authenticated %}
                            <li class="list-inline-item"><a class="social-icon pt text-xs-center" id="avathar"
                                    href="{% url 'blog:login' %}"> <i class="fa fa-user" aria-hidden="true"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                        {% if request.user.is_authenticated %}
                        <div class="off-canvas-toggle-cover d-inline-block">
                            <div class="off-canvas-toggle hidden d-inline-block" id="off-canvas-toggle">
                                <i class="fa fa-user" aria-hidden="true"></i>
                            </div>
                        </div>
                        {% endif %}
                    </div>

                    <a href="{% url 'blog:subscriptions' %}"><button
                            class="btn btn-radius bg-primary text-white ml-15 font-small box-shadow">Subscribe</button></a>

                </div>
            </div>
        </div>
    </div>
    <div class="header-sticky">
        <div class="container align-self-center position-relative">
            <div class="mobile_menu d-lg-none d-block d-flex"><button class="search-icon d-md-inline"><span
                        class="mr-15 text-muted font-small">
                        <!-- <i
                            class="elegant-icon icon_search mr-5"></i> -->
                    </span></button>
            </div>
            <div class="main-nav d-none d-lg-block float-left">
                <nav>
                    <!--Desktop menu-->
                    <ul class="main-menu d-none d-lg-inline font-small">
                        <li {% if is_index %}class="current-item has-mega-menu" {% endif %}>
                            <a href="{% url 'blog:home' %}"> <i class="elegant-icon icon_ho use_alt mr-5"></i> Home</a>

                        </li>
                        <li {% if webzin_index %}class="current-item has-mega-menu" {% endif %}> <a
                                href="{% url 'blog:latest' %}">Webzine</a> </li>
                        <li {% if is_videos %}class="current-item has-mega-menu" {% endif %}>
                            <a href="{% url 'blog:videos' %}">Videos</a>
                        </li>
                        {% for headercategory in headercategories %}
                        <li> <a href="#{{headercategory.id}}">{{headercategory.name}}</a> </li>
                        {% endfor %}
                        <li> <a href="{% url 'blog:about' %}">About Us</a> </li>
                        <li> <a href="{% url 'blog:terms' %}">Terms</a> </li>
                    </ul>



                    <!--Mobile menu-->
                    <ul id="mobile-menu" class="d-block d-lg-none text-muted">
                        <li {% if is_index %}class="current-item has-mega-menu" {% endif %}>
                            <a href="{% url 'blog:home' %}"> <i class="elegant-icon icon_ho use_alt mr-5"></i> Home</a>

                        </li>
                        <li {% if webzin_index %}class="current-item has-mega-menu" {% endif %}> <a
                                href="{% url 'blog:latest' %}">Webzine</a> </li>
                        <li {% if is_videos %}class="current-item has-mega-menu" {% endif %}>
                            <a href="{% url 'blog:videos' %}">Videos</a>
                        </li>
                        {% for headercategory in headercategories %}
                        <li> <a href="#{{headercategory.id}}">{{headercategory.name}}</a> </li>
                        {% endfor %}
                        <li> <a href="{% url 'blog:about' %}">About Us</a> </li>
                        <li> <a href="{% url 'blog:terms' %}">Terms</a> </li>
                    </ul>


                </nav>
            </div>

            <div class="float-right header-tools text-muted font-small d-block d-lg-none d-sm-block">
                <ul class="header-social-network d-inline-block list-inline mr-15">
                    <li class="list-inline-item"><a class="social-icon fb text-xs-center" target="_blank"
                            href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"><i
                                class="elegant-icon social_facebook"></i></a></li>
                    <li class="list-inline-item"><a class="social-icon tw text-xs-center" target="_blank"
                            href="https://www.twitter.com/intent/tweet?text={{instance.title|urlencode}}%20{{request.build_absolute_uri}}"><i
                                class="elegant-icon social_twitter "></i></a></li>
                    <li class="list-inline-item"><a class="social-icon pt text-xs-center" target="_blank"
                            href="https://api.whatsapp.com/send?text=*{{instance.title|urlencode}}*%0A%0A{{instance.summary|urlencode}}%0A{{request.build_absolute_uri}}"><i
                                class="fa-brands fa-whatsapp"></i></a></li>
                    {% if not request.user.is_authenticated %}
                    <li class="list-inline-item"><a class="social-icon pt text-xs-center" id="avathar"
                            href="{% url 'blog:login' %}"> <i class="fa fa-user" aria-hidden="true"></i></a></li>
                    {% endif %}
                </ul>
                {% if request.user.is_authenticated %}
                <div class="off-canvas-toggle-cover d-inline-block">
                    <div class="off-canvas-toggle hidden d-inline-block" id="off-canvas-toggle">
                        <i class="fa fa-user" aria-hidden="true"></i>
                    </div>
                </div>
                {% endif %}
            </div>

            <div class="clearfix"></div>
        </div>
    </div>
</header>

templates/web/partials/hottags.html
{% load static %}
<div class="col-md-12 text-md-right font-small align-self-center border-top border-bottom py-2">
    <p class="d-inline-block mr-5 mb-0"><i class="elegant-icon  icon_tag_alt mr-5 text-muted"></i>Hot tags:</p>
    <ul class="list-inline d-inline-block tags">
        {% for tag in tags %}
        <li class="list-inline-item"><a href="{% url 'blog:taggedarticles' tag.tag.slug %}"># {{tag.tag.name}}</a></li>
        {% endfor %}
    </ul>
</div>